### ISSUE TITLE
Support for CMake type projects

### ISSUE THREAD

**Issue by jamesbrownnz** [madskristensen/SolutionColors#1]
Would be awesome if this supported cmake type projects.
Something within the CMake targets context menu?

![image](https://user-images.githubusercontent.com/9549960/180967787-74885ee6-94da-4782-b114-eeafe7552380.png)

**Comment by madskristensen** [comment]
CMake uses the Open Folder feature instead of Solution/Projects, so by adding support for CMake, it will also work for any folder view. That would be cool!
