### ISSUE TITLE
"Show on taskbar icons" doesn't work

### ISSUE THREAD

**Issue by justdmitry** [madskristensen/SolutionColors#10]
Don't see any difference in taskbar with "Show on taskbar icons" turned on.

![devenv_2022-08-11_10-03-39](https://user-images.githubusercontent.com/3540597/184081152-edf78c5c-e21b-4d0d-a8b0-5815f693898e.png)

Tried with "Show on taskbar thumbnails" both on and off, restarted both VS after every change.

Grouping disabled in taskbar settings.

What I miss?

Windows 10, VS 17.3.0.

**Comment by madskristensen** [comment]
That is odd. Perhaps there is a difference between Windows 10 and 11, but I'm just using an API in WPF to add the overlay icon. See [this line of code](https://github.com/madskristensen/SolutionColors/blob/master/src/ColorHelper.cs#L191). Also, make sure you haven't disabled the "Show badges on taskbar apps" (that's what the setting is called in Windows 11).

**Comment by madskristensen** [comment]
This is now fixed

**Comment by justdmitry** [comment]
Oops, yes, I had "Show badges on taskbar buttons" disabled, thank you. And even grayed out due to "Use small taskbar buttons" enabled.
