### ISSUE TITLE
Same color in different repository of same project

### ISSUE THREAD

**Issue by thomasneubergersdx** [madskristensen/SolutionColors#15]
Hi Mads,

great work, great extension, but there is one thing with it that puzzles me.

I have two clones of the same remote repository on my computer. One is for my current work, the other for peeking into other branches and/or fixing my PRs.

If I set a color for the solution in my main repo, I can see the color.txt file inside of the .vs folder in the repository. If I then open the second repository, it gets the same color and I can't see why. This repository has no color.txt file in it. Once I set another color in the second repository, They each have separate colors and all works as expected.

Steps to reproduce:
1. Clone a repository
2. Clone the same repository again to another folder
3. Open the solution in repository 1 in VS
4. Set the color for the solution to something
5. Open the solution in repository 2 in VS
6. See that it has the same color as set in repository 1 (This is the wrong situation I was mentioning)
7. Set another color for slution in repository 2
8. Close and repoen both solutions and check that each have the colors set to them

What I had expected is that in step 6, the solution in repository 2 has no color set.

Kind regards
Thomas

**Comment by madskristensen** [comment]
Do you have _Auto-mode_ enabled which makes the extension automatically select a color for each solution if none is specified?

**Comment by thomasneubergersdx** [comment]
Okay, this explains why I couldn't find anything wrong in the code. It's because the bug wasn't in the software but in the stupid user (me) in front of it.
