### ISSUE TITLE
Make it configurable on a per-user basis

### ISSUE THREAD

**Issue by gamosoft** [madskristensen/SolutionColors#2]
Hello there, thanks for this simple but useful extension. :-)

My suggestion would be to make this configurable on a per user basis, instead of saving the color in the actual _.sln_ file, which is  shared across all team members, and some may not like others' chosen colors. ;-)

Thank you very much.
Kind regards.

**Comment by madskristensen** [comment]
It's not a bad idea but let me explain why I wrote the color into the .sln file. One of the scenarios where colors are helpful is when you work with multiple branches of the same repo. If you don't store the color information in the repo, then it gets lost. Now that I think about it, perhaps that is ok and you can just assign a color again when you need to. What do you think?

**Comment by gamosoft** [comment]
i (personally) wouldn't mind having to manually reassign a color

better yet, the extension could read from both places: by default from the .sln file and then from a .suo file (for example, or settings or whatever)

this way, the one in the user file would take precedence over the default in the sln file (depending on which ones are present).
if found in suo, use that, otherwise if found in sln use that, else nothing of course :-)

in any case thanks again for this extension. :-)

**Comment by gamosoft** [comment]
Thanks for this, now it's much more flexible, and in fact the .vs folder looks like a perfect place. ;-)
Just a minor annoyance, once you set up the color you cannot change it as the option is grayed out:

![image](https://user-images.githubusercontent.com/9968384/181194686-c7dc824b-5dd0-429d-8d46-cb378dfe33a5.png)

and if you manually delete the .vs folder then even if you assign the color back it doesn't work anymore (I can't see the line).

**Comment by madskristensen** [comment]
Oh, that's a bug that it is grayed out

**Comment by gamosoft** [comment]
thanks a lot, it all works now like a charm!

kind regards.
