### ISSUE TITLE
Consider adding color thumbnail to standalone editor windows

### ISSUE THREAD

**Issue by HO-COOH** [madskristensen/SolutionColors#27]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/madskristensen/SolutionColors/assets/42881734/0a191725-970f-4297-bbdf-2edafad9d300)

Quite a lot of the time, I need to jump between dragged-out standalone editor windows between two solutions, like the above. I want the solution color thumbnail to also show on those window as well.

**Describe the solution you'd like**
Show color thumbnail on all the windows created under the same solution.

**Describe alternatives you've considered**
Nope, having this extension is already boosting my productivity a lot.

**Additional context**

**Comment by HO-COOH** [comment]
I am willing to look into this and maybe implement myself :)

**Comment by madskristensen** [comment]
That would be awesome. Thanks!!

**Comment by HO-COOH** [comment]
Finished in #30
