### ISSUE TITLE
Error loading package

### ISSUE THREAD

**Issue by hannesthor** [madskristensen/SolutionColors#3]
I get the following error when loading the package:

The 'SolutionColorsPackage' package did not load correctly, The problem may have been caused by à configuration change or by the installation of another extension. You can get more information by examining the file [...]Activit Log.xml'.
Restarting Visual Studio could help resolve this issue.
Continue to show this error message?

**Comment by madskristensen** [comment]
@hannesthor thanks for reporting this issue. Do you mind opening the ActivityLog.xml and either send it to me (madsk@microsoft.com) or paste in the last couple of rows here as a comment?

**Comment by hannesthor** [comment]
Emailed

**Comment by madskristensen** [comment]
Got it. I can see what the problem is.

**Comment by madskristensen** [comment]
@hannesthor it should be fixed, but I need someone to verify it on 17.0 (which is what you seem to be running AFAICT). Can you please try the [CI build](https://www.vsixgallery.com/extension/SolutionColors.dfa813d0-736b-491d-921a-4a3503d41543) and let me know if it works for you?

**Comment by hannesthor** [comment]
Fixed!
