### ISSUE TITLE
Clarify Getting Started section instructions of the README

### ISSUE THREAD

**Issue by jp41011** [madskristensen/SolutionColors#35]
The instructions on how to enable SolutionColors are not clear for a new first-time user.
It was confusing for me, and it seems to have also confused several other users in the Q&A section for this extension in the Visual Studio Marketplace.
Reference: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.SolutionColors&ssr=false#qna

From the instructions it was not very clear What or Where I had to right click to get the context menu shown in the screenshot.

I think it might be helpful to clarify the instructions and to maybe provide a screenshot that provides more context.
Personally, it wasn't clear what the "**_it_**" in "... right-click **_it_** to select the Set Solution Color submenu..." was referring to exactly so I wasn't sure what I should be right clicking on.

I was trying to right click the Solution name that is in the middle and at the top of the Visual Studio window since that is one of the main things that stands out in all the other screenshots. It's the solution name and it colorized so I thought that was what I should to be right clicking on.

I'll submit a pull request with a suggestion, but any clarification here would be helpful.

**Comment by jp41011** [comment]
Suggested changes in pull request #36

**Comment by Arkane5** [comment]
@jp41011 I think you can close this issue, since your PR was merged.
