### ISSUE TITLE
Color is not restored on reopen

### ISSUE THREAD

**Issue by ITCBB** [madskristensen/SolutionColors#4]
Apparently the solution color is not being restored when I close and reopen the solution. 

Tested with four different solutions and on two different machines, both running Visual Studio Community 17.2.6.

**Comment by tommck** [comment]
I'm experiencing this same problem  What fixed it?

**Comment by ITCBB** [comment]
@tommck not sure, at first the colors didn't work, after a couple of days I noticed the colors were back, but took some time to appear after opening the project.
