### ISSUE TITLE
Place an overlay icon on the taskbar button

### ISSUE THREAD

**Issue by ygoe** [madskristensen/SolutionColors#7]
**Is your feature request related to a problem? Please describe.**

I use multiple Visual Studio instances regularly. I already have a tool that [separates the Visual Studio buttons on the taskbar](https://tweaker.ramensoftware.com/). Otherwise I'd go crazy with the slow procedures of the taskbar. So now I have two buttons but they look the same. Their ordering remains the same unless I close and reopen one of the windows. But they should be distinguishable to pick the right one when I'm working with the mouse.

Putting a colour bar inside the window doesn't help at all because you don't see it before you're there. The colour bar might only be a stronger indicator to know that you've landed in the wrong window again.

**Describe the solution you'd like**

There should be an overlay icon on the taskbar button to clearly identify each window. You can't go wrong when you click on the button that has the initial letters or even the icon of the project you want to work with.

There was an [extension for Visual Studio that did this](https://github.com/ashmind/SolutionIcon) but the ever-changing extensibility APIs of Visual Studio regularly breaks such useful extensions. I could hack it into VS 2019 but failed with VS 2022.

**Describe alternatives you've considered**

There is currently a workaround on another level, outside of Visual Studio, [using Windhawk](https://windhawk.net/mods/lm-vs-solution-icon). It doesn't support icons though.

**Additional context**

![grafik](https://user-images.githubusercontent.com/868315/183490831-41127d6d-1586-4f63-8f61-c7dfe5344203.png)

**Comment by madskristensen** [comment]
Got this working now:

![image](https://user-images.githubusercontent.com/1258877/183715059-4634d2af-a836-40fd-af20-c9c88d1991ae.png)

**Comment by ygoe** [comment]
Okay, but I can't use it. It doesn't help me decide on which taskbar button to click. I'm not using this preview stuff and taskbar button grouping because it takes ages for the preview to appear and then ages to disappear again. They're constantly in my way. One of the worse design decisions of the Windows 10 taskbar. It's not only about aesthetics, it's also about function.

**Comment by madskristensen** [comment]
@ygoe, check the latest version. It has an option to put the color directly on the taskbar app icons for the situation you described.
